name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Who are you?'
        required: true
        type: choice
        default: nobody
        options:
          - professor-x
          - agus
          - uri
          - manu
          - mica
          - tomi
          - nobody
      has_bucket:
        description: 'Do you own a tfstate bucket to use?'
        required: true
        type: boolean
        default: true
      create_bucket:
        description: 'Would you like to own a tfstate bucket?'
        required: true
        type: boolean
        default: false

env:
  AWS_REGION: us-east-1
  TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
  TF_VAR_bluesky_identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
  TF_VAR_bluesky_app_password: ${{ secrets.BLUESKY_APP_PASSWORD }}

jobs:
  form:
    name: Validate form data
    runs-on: ubuntu-latest

    steps:
      - name: Nobody can't create a bucket
        if: ${{ inputs.user == 'nobody' && inputs.create_bucket }}
        run: |
          echo "You are nobody, you don't deserve to own a bucket"
          exit 1

      - name: Nobody can't use a bucket
        if: ${{ inputs.user == 'nobody' && inputs.has_bucket }}
        run: |
          echo "You are nobody, you don't deserve to use a bucket"
          exit 1

      - name: Don't create bucket if already have one
        if: ${{ inputs.create_bucket && inputs.has_bucket }}
        run: |
          echo "If you already have a bucket, why did you ask me to create one?"
          exit 1

  build_lambdas:
    needs: form
    uses: ./.github/workflows/build_lambdas.yml

  setup_bootstrap:
    needs: form
    if: ${{ inputs.user != 'nobody' }}
    uses: ./.github/workflows/setup_bootstrap.yml
    with:
      user: ${{ inputs.user }}
      create: ${{ inputs.create_bucket }}

  pull_tfstate:
    if: ${{ inputs.has_bucket }}
    needs: setup_bootstrap
    uses: ./.github/workflows/pull_tfstate.yml
    with:
      user: ${{ inputs.user }}
      fail_if_missing: false

  deploy_architecture:
    name: Deploy the mainframe
    runs-on: ubuntu-latest

    needs:
      - build_lambdas
      - pull_tfstate

    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read

    outputs:
      cognito_user_pool_id: ${{ steps.vars.outputs.cognito_user_pool_id }}
      cognito_client_id: ${{ steps.vars.outputs.cognito_client_id }}
      frontend_bucket_name: ${{ steps.vars.outputs.frontend_bucket_name }}
      api_url: ${{ steps.vars.outputs.api_url }}

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: tfstate

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Give me time to reconsider my life actions
        run: sleep 60

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Capture output variables
        id: vars
        run: |
          echo cognito_user_pool_id=$(terraform output -raw cognito_user_pool_id) >> "$GITHUB_OUTPUT"
          echo cognito_client_id=$(terraform output -raw cognito_client_id) >> "$GITHUB_OUTPUT"
          echo frontend_bucket_name=$(terraform output -raw frontend_bucket_name) >> "$GITHUB_OUTPUT"
          echo api_url=$(terraform output -raw api_url) >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v7
        with:
          name: tfstate
          path: terraform/terraform.tfstate

  push_tfstate:
    if: ${{ inputs.has_bucket || inputs.create_bucket }}
    needs: deploy_architecture
    uses: ./.github/workflows/push_tfstate.yml
    with:
      user: ${{ inputs.user }}

  build_front:
    needs: deploy_architecture
    uses: ./.github/workflows/build_front.yml
    with:
      cognito_user_pool_id: ${{ needs.deploy_architecture.outputs.cognito_user_pool_id }}
      cognito_client_id: ${{ needs.deploy_architecture.outputs.cognito_client_id }}
      api_url: ${{ needs.deploy_architecture.outputs.api_url }}

  deploy_front:
    name: Deploy the mainframe
    runs-on: ubuntu-latest

    needs:
      - deploy_architecture
      - build_front

    permissions:
      contents: read

    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/download-artifact@v8
        with:
          name: front
          path: front

      - name: Push to S3 bucket
        run: aws s3 sync front/ s3://${{ needs.deploy_architecture.outputs.api_url }}/ --delete
