name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Who are you?'
        required: true
        type: choice
        options:
          - professor-x
          - agus
          - uri
          - manu
          - mica
          - tomi

env:
  AWS_REGION: us-east-1

jobs:
  pull_tfstate:
    name: Pull tfstate from bucket
    uses: ./.github/workflows/pull_tfstate.yml
    with:
      user: ${{ inputs.user }}
    secrets: inherit

  destroy:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest

    needs: pull_tfstate

    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - uses: actions/download-artifact@v8
        with:
          name: tfstate
          path: terraform

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - uses: actions/upload-artifact@v7
        with:
          name: tfstate
          path: terraform/terraform.tfstate

  push_tfstate:
    uses: ./.github/workflows/push_tfstate.yml
    with:
      user: ${{ inputs.user }}
    secrets: inherit
